package iuh.fit.ai_service.chatbot.model;

public enum ChatTool {
    PUBLIC_INFO,
    NAVIGATE_PUBLIC,
    TUTOR_MATCHING_PUBLIC,
    CLASS_MATCHING_PUBLIC,
    PUBLIC_TUTOR_LOOKUP,
    PUBLIC_CLASS_LOOKUP,
    STUDENT_MY_CLASSES,
    STUDENT_SCHEDULE,
    STUDENT_HOMEWORK,
    STUDENT_ENROLLMENT_REQUESTS,
    STUDENT_CONTRACTS,
    STUDENT_PAYMENT_STATUS,
    TUTOR_MY_CLASSES,
    TUTOR_SCHEDULE,
    TUTOR_ENROLLMENT_REQUESTS,
    TUTOR_PENDING_HOMEWORK,
    TUTOR_CONTRACTS,
    TUTOR_SETTLEMENTS,
    TUTOR_AVAILABILITY,
    STAFF_PRIVATE_DATA,
    ADMIN_PRIVATE_DATA
}
