package iuh.fit.ai_service.chatbot.model;

public enum ChatIntent {
    GENERAL_KNOWLEDGE,
    NAVIGATION,
    PRIVATE_DATA_REQUEST,
    OUT_OF_SCOPE,
    TUTOR_MATCHING,
    CLASS_MATCHING,
    PUBLIC_TUTOR_LOOKUP,
    PUBLIC_CLASS_LOOKUP,
    MY_CLASSES,
    CURRENT_SCHEDULE,
    HOMEWORK,
    ENROLLMENT_REQUESTS,
    CONTRACT_STATUS,
    PAYMENT_STATUS,
    SETTLEMENTS,
    AVAILABILITY,
    MUTATION_REQUEST
}
