package iuh.fit.ai_service.chatbot.model;

public enum NavigationAction {
    OPEN_HOME,
    OPEN_TUTOR_MARKETPLACE,
    OPEN_CLASS_MARKETPLACE,
    OPEN_LOGIN,
    OPEN_REGISTER,
    OPEN_STUDENT_CLASSES,
    OPEN_STUDENT_SCHEDULE,
    OPEN_STUDENT_HOMEWORK,
    OPEN_STUDENT_ENROLLMENT_REQUESTS,
    OPEN_STUDENT_CONTRACTS,
    OPEN_STUDENT_WALLET,
    OPEN_TUTOR_CLASSES,
    OPEN_TUTOR_SCHEDULE,
    OPEN_TUTOR_ENROLLMENT_REQUESTS,
    OPEN_TUTOR_HOMEWORK,
    OPEN_TUTOR_CONTRACTS,
    OPEN_TUTOR_AVAILABILITY
}
