services:
  postgres:
    image: postgres:16
    container_name: kltn-postgres
    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kltn_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data:
