-- DEVELOPMENT-ONLY STUDENT/TUTOR SEEDS. Not loaded by Flyway db/migration.
-- Loaded by DevelopmentDataLoader only when the Spring "dev" profile is active.

-- Plaintext development password for all 45 accounts in this file: 12345678
-- Stored value is a BCrypt hash generated by Spring Security BCryptPasswordEncoder.

WITH user_seed(
    id, email, full_name, phone, date_of_birth, gender, commune_code, address_detail, bio, role_name,
    grade, learning_goal, education, major, experience_years, tuition_min, tuition_max, submitted_at, reviewed_at
) AS (
    VALUES
        (910001, 'student1@gmail.com', 'Nguyễn Gia Huy', '0901000001', DATE '2008-03-12', 'MALE', 'HCM_SAI_GON', '12 Nguyễn Du', 'Học sinh lớp 12 cần một lộ trình ôn tập rõ ràng và đều đặn.', 'STUDENT', 'Lớp 12', 'Củng cố Toán và Vật lý, chuẩn bị cho kỳ thi tốt nghiệp THPT.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        (910002, 'student2@gmail.com', 'Trần Minh Thư', '0901000002', DATE '2010-07-22', 'FEMALE', 'HCM_BEN_THANH', '25 Lê Lai', 'Thích cách học có ví dụ trực quan và bài tập ngắn sau mỗi buổi.', 'STUDENT', 'Lớp 10', 'Cải thiện kiến thức nền Toán và Hóa, nâng cao điểm số trên lớp.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        (910003, 'student3@gmail.com', 'Lê Hoàng Anh', '0901000003', DATE '2008-01-18', 'MALE', 'HCM_CAU_ONG_LANH', '43 Trần Hưng Đạo', 'Đang xây dựng thói quen học theo mục tiêu từng tuần.', 'STUDENT', 'Lớp 12', 'Ôn tập Toán phục vụ kỳ thi tốt nghiệp và xét tuyển đại học.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        (910004, 'student4@gmail.com', 'Phạm Khánh Vy', '0901000004', DATE '2011-09-05', 'FEMALE', 'HCM_BAN_CO', '9 Cao Thắng', 'Cần gia sư kiên nhẫn, giải thích chậm và có bài luyện thêm.', 'STUDENT', 'Lớp 9', 'Củng cố Toán và Tiếng Anh, chuẩn bị kỳ thi tuyển sinh lớp 10.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        (910005, 'student5@gmail.com', 'Nguyễn Đức Minh', '0901000005', DATE '2009-11-30', 'MALE', 'HCM_XUAN_HOA', '17 Võ Văn Tần', 'Muốn học Vật lý theo hướng nắm bản chất công thức và cách biến đổi.', 'STUDENT', 'Lớp 11', 'Cải thiện kiến thức Vật lý và kỹ năng giải bài tập.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        (910006, 'student6@gmail.com', 'Võ Ngọc Hân', '0901000006', DATE '2012-04-14', 'FEMALE', 'HCM_NHIEU_LOC', '36 Nguyễn Đình Chiểu', 'Tự tin hơn khi được luyện nói và sửa lỗi nhẹ nhàng.', 'STUDENT', 'Lớp 8', 'Củng cố Tiếng Anh, đặc biệt ngữ pháp và giao tiếp cơ bản.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        (910007, 'student7@gmail.com', 'Trần Quốc Khánh', '0901000007', DATE '2006-08-01', 'MALE', 'HCM_TAN_DINH', '5 Hai Bà Trưng', 'Sinh viên mới cần nền tảng lập trình chắc để theo kịp môn học.', 'STUDENT', 'Sinh viên năm 1', 'Xây dựng nền tảng lập trình Java từ cơ bản.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        (910008, 'student8@gmail.com', 'Nguyễn Thành Đạt', '0901000008', DATE '2004-12-19', 'MALE', 'HCM_CHO_QUAN', '88 Trần Bình Trọng', 'Ưu tiên học qua project backend nhỏ và review code thực tế.', 'STUDENT', 'Sinh viên năm 3', 'Nâng cao Java, Spring Boot và SQL để xây dựng backend và project thực tế.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        (910009, 'student9@gmail.com', 'Lê Phương Linh', '0901000009', DATE '2005-06-07', 'FEMALE', 'HCM_AN_DONG', '31 An Dương Vương', 'Muốn học Python có hệ thống, kết hợp bài tập xử lý dữ liệu.', 'STUDENT', 'Sinh viên năm 2', 'Học Python và SQL để cải thiện kỹ năng lập trình và xử lý dữ liệu.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        (910010, 'student10@gmail.com', 'Phạm Tuấn Anh', '0901000010', DATE '2004-02-24', 'MALE', 'HCM_CHO_LON', '72 Nguyễn Trãi', 'Đang làm project cá nhân và cần góp ý về UI, state và API.', 'STUDENT', 'Sinh viên năm 3', 'Học React và kỹ năng frontend để hoàn thiện project cá nhân.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        (910011, 'student11@gmail.com', 'Nguyễn Quỳnh Chi', '0901000011', DATE '2003-10-11', 'FEMALE', 'HCM_BINH_TAY', '14 Hậu Giang', 'Cần lộ trình TOEIC thực dụng, tập trung nghe đọc và canh thời gian.', 'STUDENT', 'Sinh viên năm 4', 'Ôn luyện TOEIC để đáp ứng chuẩn đầu ra và tốt nghiệp.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        (910012, 'student12@gmail.com', 'Trần Bảo Ngọc', '0901000012', DATE '2009-05-27', 'FEMALE', 'HCM_HOA_HUNG', '63 Cách Mạng Tháng Tám', 'Muốn cải thiện viết học thuật và phản xạ nói tiếng Anh.', 'STUDENT', 'Lớp 11', 'Phát triển IELTS và kỹ năng Tiếng Anh học thuật.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        (910013, 'student13@gmail.com', 'Lê Nhật Minh', '0901000013', DATE '2005-01-03', 'MALE', 'HCM_VUON_LAI', '22 Lý Thường Kiệt', 'Thích bài học có ví dụ gần với bài tập chuyên ngành.', 'STUDENT', 'Sinh viên năm 2', 'Học Python từ cơ bản để phục vụ chuyên ngành và project.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        (910014, 'student14@gmail.com', 'Nguyễn Thanh Mai', '0901000014', DATE '2013-03-09', 'FEMALE', 'HCM_PHU_THO_HOA', '40 Tân Kỳ Tân Quý', 'Cần học Toán chậm, chắc, có động viên và bài tập vừa sức.', 'STUDENT', 'Lớp 7', 'Củng cố kiến thức Toán và cải thiện kết quả học tap.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        (910015, 'student15@gmail.com', 'Phạm Hoàng Long', '0901000015', DATE '2004-09-16', 'MALE', 'HCM_TAN_SON_NHI', '8 Trường Chinh', 'Muốn kết nối kiến thức SQL với Java backend trong ứng dụng thật.', 'STUDENT', 'Sinh viên năm 3', 'Nâng cao SQL và Java backend để phát triển ứng dụng.', NULL, NULL, NULL, NULL, NULL, NULL, NULL),

        (920001, 'tutor1@gmail.com', 'Nguyễn Minh Anh', '0902000001', DATE '1995-04-02', 'FEMALE', 'HCM_SAI_GON', '18 Pasteur', 'Gia sư Toán tập trung hệ thống hóa kiến thức và rèn phương pháp tư duy.', 'TUTOR', NULL, NULL, 'Cử nhân Sư phạm Toán', 'Sư phạm Toán học', 5, 180000, 250000, TIMESTAMP '2026-08-10 09:00:00', TIMESTAMP '2026-08-11 10:30:00'),
        (920002, 'tutor2@gmail.com', 'Trần Quốc Bảo', '0902000002', DATE '1996-10-21', 'MALE', 'HCM_BEN_THANH', '41 Lê Thánh Tôn', 'Kết hợp Toán và Vật lý bằng cách giải thích bản chất và cách trình bày bài.', 'TUTOR', NULL, NULL, 'Cử nhân Vật lý', 'Vật lý ứng dụng', 4, 160000, 220000, TIMESTAMP '2026-08-10 10:00:00', TIMESTAMP '2026-08-11 11:00:00'),
        (920003, 'tutor3@gmail.com', 'Lê Hoàng Nam', '0902000003', DATE '1992-02-15', 'MALE', 'HCM_CAU_ONG_LANH', '29 Ký Con', 'Có kinh nghiệm ôn thi THPT môn Toán với lộ trình rõ và bài tập phân tầng.', 'TUTOR', NULL, NULL, 'Thạc sĩ Toán học', 'Toán giải tích', 7, 250000, 350000, TIMESTAMP '2026-08-11 09:00:00', TIMESTAMP '2026-08-12 09:30:00'),
        (920004, 'tutor4@gmail.com', 'Phạm Thu Hà', '0902000004', DATE '1998-06-17', 'FEMALE', 'HCM_BAN_CO', '11 Nguyễn Thiện Thuật', 'Hướng dẫn Toán và Hóa theo cách nhẹ nhàng, phù hợp học sinh cần lấy lại gốc.', 'TUTOR', NULL, NULL, 'Cử nhân Sư phạm Hóa', 'Hóa học', 3, 140000, 200000, TIMESTAMP '2026-08-11 10:00:00', TIMESTAMP '2026-08-12 10:30:00'),
        (920005, 'tutor5@gmail.com', 'Võ Đức Long', '0902000005', DATE '1993-12-01', 'MALE', 'HCM_XUAN_HOA', '52 Điện Biên Phủ', 'Dạy Vật lý bằng sơ đồ hiện tượng, công thức và bài tập mẫu để học sinh tự tin hơn.', 'TUTOR', NULL, NULL, 'Kỹ sư Điện - Điện tử', 'Vật lý kỹ thuật', 6, 200000, 280000, TIMESTAMP '2026-08-12 09:00:00', TIMESTAMP '2026-08-13 09:30:00'),
        (920006, 'tutor6@gmail.com', 'Nguyễn Ngọc Mai', '0902000006', DATE '1994-09-09', 'FEMALE', 'HCM_NHIEU_LOC', '77 Phan Đình Phùng', 'Gia sư Hóa chú trọng liên kết lý thuyết với dạng bài và lỗi sai thường gặp.', 'TUTOR', NULL, NULL, 'Cử nhân Hóa học', 'Hóa phân tích', 5, 180000, 250000, TIMESTAMP '2026-08-12 10:00:00', TIMESTAMP '2026-08-13 10:30:00'),
        (920007, 'tutor7@gmail.com', 'Trần Khánh Linh', '0902000007', DATE '1997-05-23', 'FEMALE', 'HCM_TAN_DINH', '20 Trần Quang Khải', 'Dạy Tiếng Anh theo tình huống, sửa lỗi phát âm và ngữ pháp từng buổi.', 'TUTOR', NULL, NULL, 'Cử nhân Ngôn ngữ Anh', 'Ngôn ngữ Anh', 4, 180000, 260000, TIMESTAMP '2026-08-13 09:00:00', TIMESTAMP '2026-08-14 09:30:00'),
        (920008, 'tutor8@gmail.com', 'Lê Thảo Vy', '0902000008', DATE '1995-07-12', 'FEMALE', 'HCM_CHO_QUAN', '94 Nguyễn Trãi', 'Mạnh về TOEIC và tiếng Anh ứng dụng, có nhiều bài luyện nghe đọc ngắn.', 'TUTOR', NULL, NULL, 'Cử nhân Sư phạm Anh', 'Giảng dạy Tiếng Anh', 5, 200000, 300000, TIMESTAMP '2026-08-13 10:00:00', TIMESTAMP '2026-08-14 10:30:00'),
        (920009, 'tutor9@gmail.com', 'Nguyễn Tuấn Kiệt', '0902000009', DATE '1993-03-29', 'MALE', 'HCM_AN_DONG', '6 Nguyễn Biểu', 'Chuyên luyện TOEIC theo mục tiêu điểm và chiến lược làm bài trong thời gian giới hạn.', 'TUTOR', NULL, NULL, 'Cử nhân Ngôn ngữ Anh', 'Biên phiên dịch', 6, 250000, 350000, TIMESTAMP '2026-08-14 09:00:00', TIMESTAMP '2026-08-15 09:30:00'),
        (920010, 'tutor10@gmail.com', 'Phạm Gia Hân', '0902000010', DATE '1991-11-04', 'FEMALE', 'HCM_CHO_LON', '33 Trần Hưng Đạo B', 'Hướng dẫn IELTS và academic English bằng feedback chi tiết cho writing và speaking.', 'TUTOR', NULL, NULL, 'Thạc sĩ Ngôn ngữ Anh', 'TESOL', 7, 300000, 450000, TIMESTAMP '2026-08-14 10:00:00', TIMESTAMP '2026-08-15 10:30:00'),
        (920011, 'tutor11@gmail.com', 'Trần Minh Khoa', '0902000011', DATE '1996-01-31', 'MALE', 'HCM_BINH_TAY', '55 Bình Tây', 'Tập trung IELTS foundation đến band mục tiêu, có rubric và bài sửa hằng tuần.', 'TUTOR', NULL, NULL, 'Cử nhân Ngôn ngữ Anh', 'Tiếng Anh học thuật', 4, 280000, 380000, TIMESTAMP '2026-08-15 09:00:00', TIMESTAMP '2026-08-16 09:30:00'),
        (920012, 'tutor12@gmail.com', 'Nguyễn Phương Thảo', '0902000012', DATE '1999-08-20', 'FEMALE', 'HCM_HOA_HUNG', '10 Tô Hiến Thành', 'Dạy Tiếng Anh cơ bản cho học sinh phổ thông, ưu tiên sự tự tin và thói quen học.', 'TUTOR', NULL, NULL, 'Cử nhân Sư phạm Anh', 'Sư phạm Tiếng Anh', 3, 140000, 200000, TIMESTAMP '2026-08-15 10:00:00', TIMESTAMP '2026-08-16 10:30:00'),
        (920013, 'tutor13@gmail.com', 'Lê Quốc Huy', '0902000013', DATE '1994-02-08', 'MALE', 'HCM_VUON_LAI', '27 Âu Cơ', 'Mentor Java từ nền tảng OOP đến thực hành project nhỏ và clean code.', 'TUTOR', NULL, NULL, 'Kỹ sư Công nghệ thông tin', 'Kỹ thuật phần mềm', 5, 220000, 320000, TIMESTAMP '2026-08-16 09:00:00', TIMESTAMP '2026-08-17 09:30:00'),
        (920014, 'tutor14@gmail.com', 'Trần Đức Thịnh', '0902000014', DATE '1995-12-14', 'MALE', 'HCM_PHU_THO_HOA', '61 Lũy Bán Bích', 'Hướng dẫn Java và Spring Boot qua API thực hành, debug và review từng bước.', 'TUTOR', NULL, NULL, 'Cử nhân Khoa học máy tính', 'Backend Engineering', 4, 250000, 350000, TIMESTAMP '2026-08-16 10:00:00', TIMESTAMP '2026-08-17 10:30:00'),
        (920015, 'tutor15@gmail.com', 'Nguyễn Hoàng Phúc', '0902000015', DATE '1990-05-30', 'MALE', 'HCM_TAN_SON_NHI', '7 Trường Chinh', 'Backend mentor cho Java, Spring Boot và cơ sở dữ liệu, phù hợp sinh viên làm project.', 'TUTOR', NULL, NULL, 'Thạc sĩ Hệ thống thông tin', 'Kiến trúc phần mềm', 7, 300000, 400000, TIMESTAMP '2026-08-17 09:00:00', TIMESTAMP '2026-08-18 09:30:00'),
        (920016, 'tutor16@gmail.com', 'Phạm Anh Tú', '0902000016', DATE '1997-04-11', 'MALE', 'HCM_TAN_SON_HOA', '19 Hoàng Văn Thụ', 'Dạy Python cơ bản đến xử lý dữ liệu nhỏ, giải thích rõ cách tư duy bài toán.', 'TUTOR', NULL, NULL, 'Cử nhân Công nghệ thông tin', 'Khoa học dữ liệu', 4, 200000, 280000, TIMESTAMP '2026-08-17 10:00:00', TIMESTAMP '2026-08-18 10:30:00'),
        (920017, 'tutor17@gmail.com', 'Võ Thanh Tùng', '0902000017', DATE '1993-07-07', 'MALE', 'HCM_BAY_HIEN', '84 Lý Thường Kiệt', 'Kết hợp Python và SQL cho bài tập phân tích dữ liệu và automation đơn giản.', 'TUTOR', NULL, NULL, 'Kỹ sư Hệ thống thông tin', 'Dữ liệu và cơ sở dữ liệu', 6, 250000, 330000, TIMESTAMP '2026-08-18 09:00:00', TIMESTAMP '2026-08-19 09:30:00'),
        (920018, 'tutor18@gmail.com', 'Nguyễn Hải Yến', '0902000018', DATE '1996-06-26', 'FEMALE', 'HCM_GIA_DINH', '15 Bạch Đằng', 'Hướng dẫn React qua component, hook và kết nối API trong project frontend.', 'TUTOR', NULL, NULL, 'Cử nhân Kỹ thuật phần mềm', 'Frontend Engineering', 4, 220000, 300000, TIMESTAMP '2026-08-18 10:00:00', TIMESTAMP '2026-08-19 10:30:00'),
        (920019, 'tutor19@gmail.com', 'Lê Minh Trí', '0902000019', DATE '1994-10-03', 'MALE', 'HCM_BINH_THANH', '102 Xô Viết Nghệ Tĩnh', 'React mentor thực chiến, tập trung state management, UX và refactor code.', 'TUTOR', NULL, NULL, 'Cử nhân Công nghệ thông tin', 'Phát triển Web', 5, 250000, 350000, TIMESTAMP '2026-08-19 09:00:00', TIMESTAMP '2026-08-20 09:30:00'),
        (920020, 'tutor20@gmail.com', 'Trần Quốc Việt', '0902000020', DATE '1989-09-18', 'MALE', 'HCM_THANH_MY_TAY', '23 Đinh Bộ Lĩnh', 'Chuyên về cơ sở dữ liệu, SQL query, index và thiết kế schema cho ứng dụng.', 'TUTOR', NULL, NULL, 'Thạc sĩ Hệ thống thông tin', 'Cơ sở dữ liệu', 8, 260000, 360000, TIMESTAMP '2026-08-19 10:00:00', TIMESTAMP '2026-08-20 10:30:00'),
        (920021, 'tutor21@gmail.com', 'Nguyễn Nhật Quang', '0902000021', DATE '2000-01-25', 'MALE', 'HCM_HANH_THONG', '46 Quang Trung', 'Gia sư trẻ dạy Java và SQL theo cách gắn với bài tập trên lớp và mini app.', 'TUTOR', NULL, NULL, 'Cử nhân Công nghệ thông tin', 'Lập trình ứng dụng', 2, 150000, 220000, TIMESTAMP '2026-08-20 09:00:00', TIMESTAMP '2026-08-21 09:30:00'),
        (920022, 'tutor22@gmail.com', 'Phạm Minh Châu', '0902000022', DATE '2000-08-13', 'FEMALE', 'HCM_GO_VAP', '12 Phan Văn Trị', 'Dạy Python cho người mới, kiên nhẫn với người học bắt đầu từ con số 0.', 'TUTOR', NULL, NULL, 'Cử nhân Khoa học máy tính', 'Lập trình Python', 2, 140000, 200000, TIMESTAMP '2026-08-20 10:00:00', TIMESTAMP '2026-08-21 10:30:00'),
        (920023, 'tutor23@gmail.com', 'Lê Thanh Bình', '0902000023', DATE '1988-03-05', 'MALE', 'HCM_AN_NHON', '39 Lê Đức Thọ', 'Nhiều năm kèm Toán phổ thông, mạnh về phương pháp giải nhanh và ôn thi.', 'TUTOR', NULL, NULL, 'Cử nhân Sư phạm Toán', 'Toán ứng dụng', 8, 160000, 230000, TIMESTAMP '2026-08-21 09:00:00', TIMESTAMP '2026-08-22 09:30:00'),
        (920024, 'tutor24@gmail.com', 'Nguyễn Mỹ Duyên', '0902000024', DATE '1999-02-28', 'FEMALE', 'HCM_THU_DUC', '71 Võ Văn Ngân', 'Gia sư Hóa học gần gũi, tập trung bài tập nền tảng và ghi nhớ có logic.', 'TUTOR', NULL, NULL, 'Cử nhân Hóa học', 'Hóa hữu cơ', 2, 130000, 190000, TIMESTAMP '2026-08-21 10:00:00', TIMESTAMP '2026-08-22 10:30:00'),
        (920025, 'tutor25@gmail.com', 'Trần Anh Dũng', '0902000025', DATE '1986-12-22', 'MALE', 'HCM_LINH_XUAN', '3 Kha Vạn Cân', 'Dạy Toán và Vật lý nâng cao, phù hợp học sinh cần bứt phá điểm thi.', 'TUTOR', NULL, NULL, 'Thạc sĩ Vật lý', 'Vật lý lý thuyết', 10, 300000, 420000, TIMESTAMP '2026-08-22 09:00:00', TIMESTAMP '2026-08-23 09:30:00'),
        (920026, 'tutor26@gmail.com', 'Phạm Quỳnh Như', '0902000026', DATE '1998-11-06', 'FEMALE', 'HCM_HIEP_BINH', '58 Phạm Văn Đồng', 'Luyện TOEIC và tiếng Anh giao tiếp bằng lộ trình ngắn gọn, dễ theo dõi tiến bộ.', 'TUTOR', NULL, NULL, 'Cử nhân Ngôn ngữ Anh', 'Tiếng Anh thương mại', 3, 180000, 250000, TIMESTAMP '2026-08-22 10:00:00', TIMESTAMP '2026-08-23 10:30:00'),
        (920027, 'tutor27@gmail.com', 'Nguyễn Bảo Trâm', '0902000027', DATE '1994-01-19', 'FEMALE', 'HCM_SAI_GON', '21 Nam Kỳ Khởi Nghĩa', 'Hướng dẫn IELTS và TOEIC linh hoạt theo mục tiêu đầu ra của học viên.', 'TUTOR', NULL, NULL, 'Thạc sĩ TESOL', 'Luyện thi chứng chỉ Anh ngữ', 5, 260000, 380000, TIMESTAMP '2026-08-23 09:00:00', TIMESTAMP '2026-08-24 09:30:00'),
        (920028, 'tutor28@gmail.com', 'Lê Thành Công', '0902000028', DATE '1992-06-01', 'MALE', 'HCM_BEN_THANH', '66 Hàm Nghi', 'Backend mentor về Spring Boot, SQL và tối ưu API cho project Java.', 'TUTOR', NULL, NULL, 'Kỹ sư Phần mềm', 'Backend Java', 6, 280000, 380000, TIMESTAMP '2026-08-23 10:00:00', TIMESTAMP '2026-08-24 10:30:00'),
        (920029, 'tutor29@gmail.com', 'Trần Ngọc Ánh', '0902000029', DATE '2000-04-27', 'FEMALE', 'HCM_CAU_ONG_LANH', '30 Nguyễn Thái Học', 'Dạy Tiếng Anh nền tảng cho học sinh cần lấy lại căn bản và luyện thói quen.', 'TUTOR', NULL, NULL, 'Cử nhân Sư phạm Anh', 'Sư phạm Tiếng Anh', 2, 120000, 180000, TIMESTAMP '2026-08-24 09:00:00', TIMESTAMP '2026-08-25 09:30:00'),
        (920030, 'tutor30@gmail.com', 'Nguyễn Đình Khôi', '0902000030', DATE '1997-09-14', 'MALE', 'HCM_BAN_CO', '17 Nguyễn Đình Chiểu', 'Hướng dẫn Java và Python cho sinh viên cần nền tảng lập trình và bài tập thực hành.', 'TUTOR', NULL, NULL, 'Cử nhân Khoa học máy tính', 'Lập trình phần mềm', 3, 200000, 280000, TIMESTAMP '2026-08-24 10:00:00', TIMESTAMP '2026-08-25 10:30:00')
),
resolved_seed AS (
    SELECT
        seed.*,
        province.code AS province_code,
        province.name AS province_name,
        commune.name AS commune_name
    FROM user_seed seed
    JOIN administrative_communes commune ON commune.code = seed.commune_code
    JOIN administrative_provinces province ON province.code = commune.province_code
    WHERE province.code = 'HO_CHI_MINH'
)
INSERT INTO users (
    id, email, password, full_name, phone, date_of_birth, avatar_key, avatar_sha256, gender,
    province_code, province, commune_code, commune, address_detail, bio,
    email_verified, account_status, created_at, updated_at
)
SELECT
    id,
    email,
    '$2a$10$K5SOFrLbhxEFzWKmSIcLUutXP4Kp4mQwzxIjmWW.MrXqwcuDEJ6H2',
    full_name,
    phone,
    date_of_birth,
    NULL,
    NULL,
    gender,
    province_code,
    province_name,
    commune_code,
    commune_name,
    address_detail,
    bio,
    TRUE,
    'ACTIVE',
    COALESCE(submitted_at, TIMESTAMP '2026-08-01 09:00:00'),
    CURRENT_TIMESTAMP
FROM resolved_seed
ON CONFLICT (email) DO UPDATE SET
    password = EXCLUDED.password,
    full_name = EXCLUDED.full_name,
    phone = EXCLUDED.phone,
    date_of_birth = EXCLUDED.date_of_birth,
    gender = EXCLUDED.gender,
    province_code = EXCLUDED.province_code,
    province = EXCLUDED.province,
    commune_code = EXCLUDED.commune_code,
    commune = EXCLUDED.commune,
    address_detail = EXCLUDED.address_detail,
    bio = EXCLUDED.bio,
    email_verified = TRUE,
    account_status = 'ACTIVE',
    updated_at = CURRENT_TIMESTAMP;

WITH role_seed(email, role_name) AS (
    VALUES
        ('student1@gmail.com', 'STUDENT'), ('student2@gmail.com', 'STUDENT'), ('student3@gmail.com', 'STUDENT'), ('student4@gmail.com', 'STUDENT'), ('student5@gmail.com', 'STUDENT'),
        ('student6@gmail.com', 'STUDENT'), ('student7@gmail.com', 'STUDENT'), ('student8@gmail.com', 'STUDENT'), ('student9@gmail.com', 'STUDENT'), ('student10@gmail.com', 'STUDENT'),
        ('student11@gmail.com', 'STUDENT'), ('student12@gmail.com', 'STUDENT'), ('student13@gmail.com', 'STUDENT'), ('student14@gmail.com', 'STUDENT'), ('student15@gmail.com', 'STUDENT'),
        ('tutor1@gmail.com', 'TUTOR'), ('tutor2@gmail.com', 'TUTOR'), ('tutor3@gmail.com', 'TUTOR'), ('tutor4@gmail.com', 'TUTOR'), ('tutor5@gmail.com', 'TUTOR'),
        ('tutor6@gmail.com', 'TUTOR'), ('tutor7@gmail.com', 'TUTOR'), ('tutor8@gmail.com', 'TUTOR'), ('tutor9@gmail.com', 'TUTOR'), ('tutor10@gmail.com', 'TUTOR'),
        ('tutor11@gmail.com', 'TUTOR'), ('tutor12@gmail.com', 'TUTOR'), ('tutor13@gmail.com', 'TUTOR'), ('tutor14@gmail.com', 'TUTOR'), ('tutor15@gmail.com', 'TUTOR'),
        ('tutor16@gmail.com', 'TUTOR'), ('tutor17@gmail.com', 'TUTOR'), ('tutor18@gmail.com', 'TUTOR'), ('tutor19@gmail.com', 'TUTOR'), ('tutor20@gmail.com', 'TUTOR'),
        ('tutor21@gmail.com', 'TUTOR'), ('tutor22@gmail.com', 'TUTOR'), ('tutor23@gmail.com', 'TUTOR'), ('tutor24@gmail.com', 'TUTOR'), ('tutor25@gmail.com', 'TUTOR'),
        ('tutor26@gmail.com', 'TUTOR'), ('tutor27@gmail.com', 'TUTOR'), ('tutor28@gmail.com', 'TUTOR'), ('tutor29@gmail.com', 'TUTOR'), ('tutor30@gmail.com', 'TUTOR')
)
INSERT INTO user_roles (user_id, role)
SELECT app_user.id, role_seed.role_name
FROM role_seed
JOIN users app_user ON LOWER(app_user.email) = role_seed.email
ON CONFLICT (user_id, role) DO NOTHING;

WITH student_seed(email, grade, learning_goal) AS (
    VALUES
        ('student1@gmail.com', 'Lớp 12', 'Củng cố Toán và Vật lý, chuẩn bị cho kỳ thi tốt nghiệp THPT.'),
        ('student2@gmail.com', 'Lớp 10', 'Cải thiện kiến thức nền Toán và Hóa, nâng cao điểm số trên lớp.'),
        ('student3@gmail.com', 'Lớp 12', 'Ôn tập Toán phục vụ kỳ thi tốt nghiệp và xét tuyển đại học.'),
        ('student4@gmail.com', 'Lớp 9', 'Củng cố Toán và Tiếng Anh, chuẩn bị kỳ thi tuyển sinh lớp 10.'),
        ('student5@gmail.com', 'Lớp 11', 'Cải thiện kiến thức Vật lý và kỹ năng giải bài tập.'),
        ('student6@gmail.com', 'Lớp 8', 'Củng cố Tiếng Anh, đặc biệt ngữ pháp và giao tiếp cơ bản.'),
        ('student7@gmail.com', 'Sinh viên năm 1', 'Xây dựng nền tảng lập trình Java từ cơ bản.'),
        ('student8@gmail.com', 'Sinh viên năm 3', 'Nâng cao Java, Spring Boot và SQL để xây dựng backend và project thực tế.'),
        ('student9@gmail.com', 'Sinh viên năm 2', 'Học Python và SQL để cải thiện kỹ năng lập trình và xử lý dữ liệu.'),
        ('student10@gmail.com', 'Sinh viên năm 3', 'Học React và kỹ năng frontend để hoàn thiện project cá nhân.'),
        ('student11@gmail.com', 'Sinh viên năm 4', 'Ôn luyện TOEIC để đáp ứng chuẩn đầu ra và tốt nghiệp.'),
        ('student12@gmail.com', 'Lớp 11', 'Phát triển IELTS và kỹ năng Tiếng Anh học thuật.'),
        ('student13@gmail.com', 'Sinh viên năm 2', 'Học Python từ cơ bản để phục vụ chuyên ngành và project.'),
        ('student14@gmail.com', 'Lớp 7', 'Củng cố kiến thức Toán và cải thiện kết quả học tap.'),
        ('student15@gmail.com', 'Sinh viên năm 3', 'Nâng cao SQL và Java backend để phát triển ứng dụng.')
)
INSERT INTO students (user_id, grade, learning_goal)
SELECT app_user.id, seed.grade, seed.learning_goal
FROM student_seed seed
JOIN users app_user ON LOWER(app_user.email) = seed.email
ON CONFLICT (user_id) DO UPDATE SET
    grade = EXCLUDED.grade,
    learning_goal = EXCLUDED.learning_goal;

WITH tutor_seed(email, tutor_id, bio, education, experience_years) AS (
    VALUES
        ('tutor1@gmail.com', 920001, 'Gia sư Toán tập trung hệ thống hóa kiến thức và rèn phương pháp tư duy.', 'Cử nhân Sư phạm Toán', 5),
        ('tutor2@gmail.com', 920002, 'Kết hợp Toán và Vật lý bằng cách giải thích bản chất và cách trình bày bài.', 'Cử nhân Vật lý', 4),
        ('tutor3@gmail.com', 920003, 'Có kinh nghiệm ôn thi THPT môn Toán với lộ trình rõ và bài tập phân tầng.', 'Thạc sĩ Toán học', 7),
        ('tutor4@gmail.com', 920004, 'Hướng dẫn Toán và Hóa theo cách nhẹ nhàng, phù hợp học sinh cần lấy lại gốc.', 'Cử nhân Sư phạm Hóa', 3),
        ('tutor5@gmail.com', 920005, 'Dạy Vật lý bằng sơ đồ hiện tượng, công thức và bài tập mẫu để học sinh tự tin hơn.', 'Kỹ sư Điện - Điện tử', 6),
        ('tutor6@gmail.com', 920006, 'Gia sư Hóa chú trọng liên kết lý thuyết với dạng bài và lỗi sai thường gặp.', 'Cử nhân Hóa học', 5),
        ('tutor7@gmail.com', 920007, 'Dạy Tiếng Anh theo tình huống, sửa lỗi phát âm và ngữ pháp từng buổi.', 'Cử nhân Ngôn ngữ Anh', 4),
        ('tutor8@gmail.com', 920008, 'Mạnh về TOEIC và tiếng Anh ứng dụng, có nhiều bài luyện nghe đọc ngắn.', 'Cử nhân Sư phạm Anh', 5),
        ('tutor9@gmail.com', 920009, 'Chuyên luyện TOEIC theo mục tiêu điểm và chiến lược làm bài trong thời gian giới hạn.', 'Cử nhân Ngôn ngữ Anh', 6),
        ('tutor10@gmail.com', 920010, 'Hướng dẫn IELTS và academic English bằng feedback chi tiết cho writing và speaking.', 'Thạc sĩ Ngôn ngữ Anh', 7),
        ('tutor11@gmail.com', 920011, 'Tập trung IELTS foundation đến band mục tiêu, có rubric và bài sửa hằng tuần.', 'Cử nhân Ngôn ngữ Anh', 4),
        ('tutor12@gmail.com', 920012, 'Dạy Tiếng Anh cơ bản cho học sinh phổ thông, ưu tiên sự tự tin và thói quen học.', 'Cử nhân Sư phạm Anh', 3),
        ('tutor13@gmail.com', 920013, 'Mentor Java từ nền tảng OOP đến thực hành project nhỏ và clean code.', 'Kỹ sư Công nghệ thông tin', 5),
        ('tutor14@gmail.com', 920014, 'Hướng dẫn Java và Spring Boot qua API thực hành, debug và review từng bước.', 'Cử nhân Khoa học máy tính', 4),
        ('tutor15@gmail.com', 920015, 'Backend mentor cho Java, Spring Boot và cơ sở dữ liệu, phù hợp sinh viên làm project.', 'Thạc sĩ Hệ thống thông tin', 7),
        ('tutor16@gmail.com', 920016, 'Dạy Python cơ bản đến xử lý dữ liệu nhỏ, giải thích rõ cách tư duy bài toán.', 'Cử nhân Công nghệ thông tin', 4),
        ('tutor17@gmail.com', 920017, 'Kết hợp Python và SQL cho bài tập phân tích dữ liệu và automation đơn giản.', 'Kỹ sư Hệ thống thông tin', 6),
        ('tutor18@gmail.com', 920018, 'Hướng dẫn React qua component, hook và kết nối API trong project frontend.', 'Cử nhân Kỹ thuật phần mềm', 4),
        ('tutor19@gmail.com', 920019, 'React mentor thực chiến, tập trung state management, UX và refactor code.', 'Cử nhân Công nghệ thông tin', 5),
        ('tutor20@gmail.com', 920020, 'Chuyên về cơ sở dữ liệu, SQL query, index và thiết kế schema cho ứng dụng.', 'Thạc sĩ Hệ thống thông tin', 8),
        ('tutor21@gmail.com', 920021, 'Gia sư trẻ dạy Java và SQL theo cách gắn với bài tập trên lớp và mini app.', 'Cử nhân Công nghệ thông tin', 2),
        ('tutor22@gmail.com', 920022, 'Dạy Python cho người mới, kiên nhẫn với người học bắt đầu từ con số 0.', 'Cử nhân Khoa học máy tính', 2),
        ('tutor23@gmail.com', 920023, 'Nhiều năm kèm Toán phổ thông, mạnh về phương pháp giải nhanh và ôn thi.', 'Cử nhân Sư phạm Toán', 8),
        ('tutor24@gmail.com', 920024, 'Gia sư Hóa học gần gũi, tập trung bài tập nền tảng và ghi nhớ có logic.', 'Cử nhân Hóa học', 2),
        ('tutor25@gmail.com', 920025, 'Dạy Toán và Vật lý nâng cao, phù hợp học sinh cần bứt phá điểm thi.', 'Thạc sĩ Vật lý', 10),
        ('tutor26@gmail.com', 920026, 'Luyện TOEIC và tiếng Anh giao tiếp bằng lộ trình ngắn gọn, dễ theo dõi tiến bộ.', 'Cử nhân Ngôn ngữ Anh', 3),
        ('tutor27@gmail.com', 920027, 'Hướng dẫn IELTS và TOEIC linh hoạt theo mục tiêu đầu ra của học viên.', 'Thạc sĩ TESOL', 5),
        ('tutor28@gmail.com', 920028, 'Backend mentor về Spring Boot, SQL và tối ưu API cho project Java.', 'Kỹ sư Phần mềm', 6),
        ('tutor29@gmail.com', 920029, 'Dạy Tiếng Anh nền tảng cho học sinh cần lấy lại căn bản và luyện thói quen.', 'Cử nhân Sư phạm Anh', 2),
        ('tutor30@gmail.com', 920030, 'Hướng dẫn Java và Python cho sinh viên cần nền tảng lập trình và bài tập thực hành.', 'Cử nhân Khoa học máy tính', 3)
)
INSERT INTO tutors (id, user_id, bio, education, experience_years, verification_status, status, created_at, updated_at)
SELECT seed.tutor_id, app_user.id, seed.bio, seed.education, seed.experience_years, 'APPROVED', 'APPROVED', TIMESTAMP '2026-08-10 09:00:00', CURRENT_TIMESTAMP
FROM tutor_seed seed
JOIN users app_user ON LOWER(app_user.email) = seed.email
ON CONFLICT (user_id) DO UPDATE SET
    bio = EXCLUDED.bio,
    education = EXCLUDED.education,
    experience_years = EXCLUDED.experience_years,
    verification_status = 'APPROVED',
    status = 'APPROVED',
    updated_at = CURRENT_TIMESTAMP;

WITH tutor_profiles_seed AS (
    SELECT tutor.id AS tutor_id, tutor.user_id, tutor.bio
    FROM tutors tutor
    JOIN users app_user ON app_user.id = tutor.user_id
    WHERE LOWER(app_user.email) BETWEEN 'tutor1@gmail.com' AND 'tutor9@gmail.com'
       OR LOWER(app_user.email) LIKE 'tutor1%@gmail.com'
       OR LOWER(app_user.email) LIKE 'tutor2%@gmail.com'
       OR LOWER(app_user.email) LIKE 'tutor30@gmail.com'
)
INSERT INTO tutor_profiles (id, user_id, active, bio, created_at, updated_at)
SELECT tutor_id, user_id, TRUE, bio, TIMESTAMP '2026-08-10 09:00:00', CURRENT_TIMESTAMP
FROM tutor_profiles_seed
ON CONFLICT (user_id) DO UPDATE SET
    active = TRUE,
    bio = EXCLUDED.bio,
    updated_at = CURRENT_TIMESTAMP;

WITH application_seed(email, bio, education_level, institution, major, experience_summary, submitted_at, reviewed_at) AS (
    SELECT email, bio, education, 'EduConnect Development Faculty', major,
           'Đã được duyệt trong bộ dữ liệu development để hỗ trợ demo và kiểm thử Account/Learning.',
           submitted_at, reviewed_at
    FROM (
        VALUES
            ('tutor1@gmail.com', 'Gia sư Toán tập trung hệ thống hóa kiến thức và rèn phương pháp tư duy.', 'Đại học', 'Sư phạm Toán học', TIMESTAMP '2026-08-10 09:00:00', TIMESTAMP '2026-08-11 10:30:00'),
            ('tutor2@gmail.com', 'Kết hợp Toán và Vật lý bằng cách giải thích bản chất và cách trình bày bài.', 'Đại học', 'Vật lý ứng dụng', TIMESTAMP '2026-08-10 10:00:00', TIMESTAMP '2026-08-11 11:00:00'),
            ('tutor3@gmail.com', 'Có kinh nghiệm ôn thi THPT môn Toán với lộ trình rõ và bài tập phân tầng.', 'Thạc sĩ', 'Toán giải tích', TIMESTAMP '2026-08-11 09:00:00', TIMESTAMP '2026-08-12 09:30:00'),
            ('tutor4@gmail.com', 'Hướng dẫn Toán và Hóa theo cách nhẹ nhàng, phù hợp học sinh cần lấy lại gốc.', 'Đại học', 'Hóa học', TIMESTAMP '2026-08-11 10:00:00', TIMESTAMP '2026-08-12 10:30:00'),
            ('tutor5@gmail.com', 'Dạy Vật lý bằng sơ đồ hiện tượng, công thức và bài tập mẫu để học sinh tự tin hơn.', 'Đại học', 'Vật lý kỹ thuật', TIMESTAMP '2026-08-12 09:00:00', TIMESTAMP '2026-08-13 09:30:00'),
            ('tutor6@gmail.com', 'Gia sư Hóa chú trọng liên kết lý thuyết với dạng bài và lỗi sai thường gặp.', 'Đại học', 'Hóa phân tích', TIMESTAMP '2026-08-12 10:00:00', TIMESTAMP '2026-08-13 10:30:00'),
            ('tutor7@gmail.com', 'Dạy Tiếng Anh theo tình huống, sửa lỗi phát âm và ngữ pháp từng buổi.', 'Đại học', 'Ngôn ngữ Anh', TIMESTAMP '2026-08-13 09:00:00', TIMESTAMP '2026-08-14 09:30:00'),
            ('tutor8@gmail.com', 'Mạnh về TOEIC và tiếng Anh ứng dụng, có nhiều bài luyện nghe đọc ngắn.', 'Đại học', 'Giảng dạy Tiếng Anh', TIMESTAMP '2026-08-13 10:00:00', TIMESTAMP '2026-08-14 10:30:00'),
            ('tutor9@gmail.com', 'Chuyên luyện TOEIC theo mục tiêu điểm và chiến lược làm bài trong thời gian giới hạn.', 'Đại học', 'Biên phiên dịch', TIMESTAMP '2026-08-14 09:00:00', TIMESTAMP '2026-08-15 09:30:00'),
            ('tutor10@gmail.com', 'Hướng dẫn IELTS và academic English bằng feedback chi tiết cho writing và speaking.', 'Thạc sĩ', 'TESOL', TIMESTAMP '2026-08-14 10:00:00', TIMESTAMP '2026-08-15 10:30:00'),
            ('tutor11@gmail.com', 'Tập trung IELTS foundation đến band mục tiêu, có rubric và bài sửa hằng tuần.', 'Đại học', 'Tiếng Anh học thuật', TIMESTAMP '2026-08-15 09:00:00', TIMESTAMP '2026-08-16 09:30:00'),
            ('tutor12@gmail.com', 'Dạy Tiếng Anh cơ bản cho học sinh phổ thông, ưu tiên sự tự tin và thói quen học.', 'Đại học', 'Sư phạm Tiếng Anh', TIMESTAMP '2026-08-15 10:00:00', TIMESTAMP '2026-08-16 10:30:00'),
            ('tutor13@gmail.com', 'Mentor Java từ nền tảng OOP đến thực hành project nhỏ và clean code.', 'Đại học', 'Kỹ thuật phần mềm', TIMESTAMP '2026-08-16 09:00:00', TIMESTAMP '2026-08-17 09:30:00'),
            ('tutor14@gmail.com', 'Hướng dẫn Java và Spring Boot qua API thực hành, debug và review từng bước.', 'Đại học', 'Backend Engineering', TIMESTAMP '2026-08-16 10:00:00', TIMESTAMP '2026-08-17 10:30:00'),
            ('tutor15@gmail.com', 'Backend mentor cho Java, Spring Boot và cơ sở dữ liệu, phù hợp sinh viên làm project.', 'Thạc sĩ', 'Kiến trúc phần mềm', TIMESTAMP '2026-08-17 09:00:00', TIMESTAMP '2026-08-18 09:30:00'),
            ('tutor16@gmail.com', 'Dạy Python cơ bản đến xử lý dữ liệu nhỏ, giải thích rõ cách tư duy bài toán.', 'Đại học', 'Khoa học dữ liệu', TIMESTAMP '2026-08-17 10:00:00', TIMESTAMP '2026-08-18 10:30:00'),
            ('tutor17@gmail.com', 'Kết hợp Python và SQL cho bài tập phân tích dữ liệu và automation đơn giản.', 'Đại học', 'Dữ liệu và cơ sở dữ liệu', TIMESTAMP '2026-08-18 09:00:00', TIMESTAMP '2026-08-19 09:30:00'),
            ('tutor18@gmail.com', 'Hướng dẫn React qua component, hook và kết nối API trong project frontend.', 'Đại học', 'Frontend Engineering', TIMESTAMP '2026-08-18 10:00:00', TIMESTAMP '2026-08-19 10:30:00'),
            ('tutor19@gmail.com', 'React mentor thực chiến, tập trung state management, UX và refactor code.', 'Đại học', 'Phát triển Web', TIMESTAMP '2026-08-19 09:00:00', TIMESTAMP '2026-08-20 09:30:00'),
            ('tutor20@gmail.com', 'Chuyên về cơ sở dữ liệu, SQL query, index và thiết kế schema cho ứng dụng.', 'Thạc sĩ', 'Cơ sở dữ liệu', TIMESTAMP '2026-08-19 10:00:00', TIMESTAMP '2026-08-20 10:30:00'),
            ('tutor21@gmail.com', 'Gia sư trẻ dạy Java và SQL theo cách gắn với bài tập trên lớp và mini app.', 'Đại học', 'Lập trình ứng dụng', TIMESTAMP '2026-08-20 09:00:00', TIMESTAMP '2026-08-21 09:30:00'),
            ('tutor22@gmail.com', 'Dạy Python cho người mới, kiên nhẫn với người học bắt đầu từ con số 0.', 'Đại học', 'Lập trình Python', TIMESTAMP '2026-08-20 10:00:00', TIMESTAMP '2026-08-21 10:30:00'),
            ('tutor23@gmail.com', 'Nhiều năm kèm Toán phổ thông, mạnh về phương pháp giải nhanh và ôn thi.', 'Đại học', 'Toán ứng dụng', TIMESTAMP '2026-08-21 09:00:00', TIMESTAMP '2026-08-22 09:30:00'),
            ('tutor24@gmail.com', 'Gia sư Hóa học gần gũi, tập trung bài tập nền tảng và ghi nhớ có logic.', 'Đại học', 'Hóa hữu cơ', TIMESTAMP '2026-08-21 10:00:00', TIMESTAMP '2026-08-22 10:30:00'),
            ('tutor25@gmail.com', 'Dạy Toán và Vật lý nâng cao, phù hợp học sinh cần bứt phá điểm thi.', 'Thạc sĩ', 'Vật lý lý thuyết', TIMESTAMP '2026-08-22 09:00:00', TIMESTAMP '2026-08-23 09:30:00'),
            ('tutor26@gmail.com', 'Luyện TOEIC và tiếng Anh giao tiếp bằng lộ trình ngắn gọn, dễ theo dõi tiến bộ.', 'Đại học', 'Tiếng Anh thương mại', TIMESTAMP '2026-08-22 10:00:00', TIMESTAMP '2026-08-23 10:30:00'),
            ('tutor27@gmail.com', 'Hướng dẫn IELTS và TOEIC linh hoạt theo mục tiêu đầu ra của học viên.', 'Thạc sĩ', 'Luyện thi chứng chỉ Anh ngữ', TIMESTAMP '2026-08-23 09:00:00', TIMESTAMP '2026-08-24 09:30:00'),
            ('tutor28@gmail.com', 'Backend mentor về Spring Boot, SQL và tối ưu API cho project Java.', 'Đại học', 'Backend Java', TIMESTAMP '2026-08-23 10:00:00', TIMESTAMP '2026-08-24 10:30:00'),
            ('tutor29@gmail.com', 'Dạy Tiếng Anh nền tảng cho học sinh cần lấy lại căn bản và luyện thói quen.', 'Đại học', 'Sư phạm Tiếng Anh', TIMESTAMP '2026-08-24 09:00:00', TIMESTAMP '2026-08-25 09:30:00'),
            ('tutor30@gmail.com', 'Hướng dẫn Java và Python cho sinh viên cần nền tảng lập trình và bài tập thực hành.', 'Đại học', 'Lập trình phần mềm', TIMESTAMP '2026-08-24 10:00:00', TIMESTAMP '2026-08-25 10:30:00')
    ) AS raw(email, bio, education, major, submitted_at, reviewed_at)
),
reviewer AS (
    SELECT id FROM users WHERE LOWER(email) = 'ngocquocthai.004@gmail.com'
    UNION ALL
    SELECT id FROM users WHERE LOWER(email) = 'tanthinh@gmail.com'
    ORDER BY id
    LIMIT 1
)
INSERT INTO tutor_applications (
    user_id, status, bio, education_level, institution, major, experience_summary,
    submitted_at, reviewed_at, reviewed_by, review_note,
    applicant_full_name, applicant_email, applicant_phone, applicant_date_of_birth, applicant_gender,
    applicant_province_code, applicant_province_name, applicant_commune_code, applicant_commune_name,
    applicant_address_detail, applicant_avatar_key, created_at, updated_at
)
SELECT
    app_user.id,
    'APPROVED',
    seed.bio,
    seed.education_level,
    seed.institution,
    seed.major,
    seed.experience_summary,
    seed.submitted_at,
    seed.reviewed_at,
    (SELECT id FROM reviewer),
    'Approved development dataset tutor profile.',
    app_user.full_name,
    app_user.email,
    app_user.phone,
    app_user.date_of_birth,
    app_user.gender,
    app_user.province_code,
    app_user.province,
    app_user.commune_code,
    app_user.commune,
    app_user.address_detail,
    app_user.avatar_key,
    seed.submitted_at,
    CURRENT_TIMESTAMP
FROM application_seed seed
JOIN users app_user ON LOWER(app_user.email) = seed.email
ON CONFLICT (user_id) DO UPDATE SET
    status = 'APPROVED',
    bio = EXCLUDED.bio,
    education_level = EXCLUDED.education_level,
    institution = EXCLUDED.institution,
    major = EXCLUDED.major,
    experience_summary = EXCLUDED.experience_summary,
    submitted_at = EXCLUDED.submitted_at,
    reviewed_at = EXCLUDED.reviewed_at,
    reviewed_by = EXCLUDED.reviewed_by,
    review_note = EXCLUDED.review_note,
    applicant_full_name = EXCLUDED.applicant_full_name,
    applicant_email = EXCLUDED.applicant_email,
    applicant_phone = EXCLUDED.applicant_phone,
    applicant_date_of_birth = EXCLUDED.applicant_date_of_birth,
    applicant_gender = EXCLUDED.applicant_gender,
    applicant_province_code = EXCLUDED.applicant_province_code,
    applicant_province_name = EXCLUDED.applicant_province_name,
    applicant_commune_code = EXCLUDED.applicant_commune_code,
    applicant_commune_name = EXCLUDED.applicant_commune_name,
    applicant_address_detail = EXCLUDED.applicant_address_detail,
    applicant_avatar_key = EXCLUDED.applicant_avatar_key,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO tutor_application_teaching_modes (tutor_application_id, teaching_mode)
SELECT app.id, mode
FROM tutor_applications app
JOIN users app_user ON app.user_id = app_user.id
CROSS JOIN (VALUES ('ONLINE'), ('OFFLINE')) AS modes(mode)
WHERE LOWER(app_user.email) IN (
    'tutor1@gmail.com', 'tutor2@gmail.com', 'tutor3@gmail.com', 'tutor4@gmail.com', 'tutor5@gmail.com',
    'tutor6@gmail.com', 'tutor7@gmail.com', 'tutor8@gmail.com', 'tutor9@gmail.com', 'tutor10@gmail.com',
    'tutor11@gmail.com', 'tutor12@gmail.com', 'tutor13@gmail.com', 'tutor14@gmail.com', 'tutor15@gmail.com',
    'tutor16@gmail.com', 'tutor17@gmail.com', 'tutor18@gmail.com', 'tutor19@gmail.com', 'tutor20@gmail.com',
    'tutor21@gmail.com', 'tutor22@gmail.com', 'tutor23@gmail.com', 'tutor24@gmail.com', 'tutor25@gmail.com',
    'tutor26@gmail.com', 'tutor27@gmail.com', 'tutor28@gmail.com', 'tutor29@gmail.com', 'tutor30@gmail.com'
)
ON CONFLICT (tutor_application_id, teaching_mode) DO NOTHING;

WITH app_subject_seed(email, legacy_subject_id, subject_name, category_name, group_name, rate, experience_years, description) AS (
    VALUES
        ('tutor1@gmail.com', 13, 'Toán học', 'Khoa học', 'Toán học', 180000, 5, 'Củng cố kiến thức Toán THPT và ôn thi có lộ trình.'),
        ('tutor2@gmail.com', 13, 'Toán học', 'Khoa học', 'Toán học', 160000, 4, 'Kèm Toán kết hợp phương pháp giải bài rõ ràng.'),
        ('tutor2@gmail.com', 20, 'Vật lý', 'Khoa học', 'Vật lý - Hóa học - Sinh học', 180000, 4, 'Giải thích hiện tượng Vật lý và luyện dạng bài.'),
        ('tutor3@gmail.com', 13, 'Toán học', 'Khoa học', 'Toán học', 250000, 7, 'Ôn thi THPT môn Toán nâng cao.'),
        ('tutor4@gmail.com', 13, 'Toán học', 'Khoa học', 'Toán học', 140000, 3, 'Lấy lại gốc Toán và luyện bài trên lớp.'),
        ('tutor4@gmail.com', 21, 'Hóa học', 'Khoa học', 'Vật lý - Hóa học - Sinh học', 150000, 3, 'Hóa học nền tảng cho học sinh THPT.'),
        ('tutor5@gmail.com', 20, 'Vật lý', 'Khoa học', 'Vật lý - Hóa học - Sinh học', 200000, 6, 'Vật lý THPT theo sơ đồ công thức và bài mẫu.'),
        ('tutor6@gmail.com', 21, 'Hóa học', 'Khoa học', 'Vật lý - Hóa học - Sinh học', 180000, 5, 'Hóa học theo chuyên đề và lỗi sai thường gặp.'),
        ('tutor7@gmail.com', 1, 'Tiếng Anh', 'Ngoại ngữ', 'Tiếng Anh', 180000, 4, 'Ngữ pháp và giao tiếp tiếng Anh phổ thông.'),
        ('tutor8@gmail.com', 1, 'Tiếng Anh', 'Ngoại ngữ', 'Tiếng Anh', 200000, 5, 'Tiếng Anh ứng dụng kết hợp luyện nghe nói.'),
        ('tutor8@gmail.com', 4, 'TOEIC', 'Ngoại ngữ', 'Tiếng Anh', 240000, 5, 'TOEIC nghe đọc theo mục tiêu điểm.'),
        ('tutor9@gmail.com', 4, 'TOEIC', 'Ngoại ngữ', 'Tiếng Anh', 250000, 6, 'Luyện TOEIC có chiến lược làm bài.'),
        ('tutor10@gmail.com', 3, 'IELTS', 'Ngoại ngữ', 'Tiếng Anh', 330000, 7, 'IELTS writing và speaking feedback chi tiết.'),
        ('tutor10@gmail.com', 1, 'Tiếng Anh', 'Ngoại ngữ', 'Tiếng Anh', 300000, 7, 'Academic English cho học sinh THPT.'),
        ('tutor11@gmail.com', 3, 'IELTS', 'Ngoại ngữ', 'Tiếng Anh', 280000, 4, 'IELTS foundation đến band mục tiêu.'),
        ('tutor12@gmail.com', 1, 'Tiếng Anh', 'Ngoại ngữ', 'Tiếng Anh', 140000, 3, 'Tiếng Anh cơ bản cho học sinh phổ thông.'),
        ('tutor13@gmail.com', 38, 'Java', 'Công nghệ thông tin', 'Lập trình', 220000, 5, 'Java core, OOP và project nhỏ.'),
        ('tutor14@gmail.com', 38, 'Java', 'Công nghệ thông tin', 'Lập trình', 250000, 4, 'Java backend nền tảng.'),
        ('tutor14@gmail.com', 45, 'Spring Boot', 'Công nghệ thông tin', 'Web Development', 280000, 4, 'Spring Boot REST API và validation.'),
        ('tutor15@gmail.com', 38, 'Java', 'Công nghệ thông tin', 'Lập trình', 300000, 7, 'Java backend thực chiến.'),
        ('tutor15@gmail.com', 45, 'Spring Boot', 'Công nghệ thông tin', 'Web Development', 320000, 7, 'Spring Boot project mentoring.'),
        ('tutor15@gmail.com', 55, 'SQL', 'Công nghệ thông tin', 'Cơ sở dữ liệu', 300000, 7, 'SQL và thiết kế schema cho backend.'),
        ('tutor16@gmail.com', 42, 'Python', 'Công nghệ thông tin', 'Lập trình', 200000, 4, 'Python cơ bản và xử lý dữ liệu.'),
        ('tutor17@gmail.com', 42, 'Python', 'Công nghệ thông tin', 'Lập trình', 250000, 6, 'Python automation và data exercise.'),
        ('tutor17@gmail.com', 55, 'SQL', 'Công nghệ thông tin', 'Cơ sở dữ liệu', 260000, 6, 'SQL query, join và aggregation.'),
        ('tutor18@gmail.com', 46, 'React', 'Công nghệ thông tin', 'Web Development', 220000, 4, 'React component, hooks và API.'),
        ('tutor19@gmail.com', 46, 'React', 'Công nghệ thông tin', 'Web Development', 250000, 5, 'React state management và refactor.'),
        ('tutor20@gmail.com', 55, 'SQL', 'Công nghệ thông tin', 'Cơ sở dữ liệu', 260000, 8, 'SQL, index và thiết kế database.'),
        ('tutor21@gmail.com', 38, 'Java', 'Công nghệ thông tin', 'Lập trình', 150000, 2, 'Java cơ bản cho sinh viên.'),
        ('tutor21@gmail.com', 55, 'SQL', 'Công nghệ thông tin', 'Cơ sở dữ liệu', 160000, 2, 'SQL nền tảng cho bài tập trên lớp.'),
        ('tutor22@gmail.com', 42, 'Python', 'Công nghệ thông tin', 'Lập trình', 140000, 2, 'Python cho người mới bắt đầu.'),
        ('tutor23@gmail.com', 13, 'Toán học', 'Khoa học', 'Toán học', 160000, 8, 'Toán phổ thông và ôn thi.'),
        ('tutor24@gmail.com', 21, 'Hóa học', 'Khoa học', 'Vật lý - Hóa học - Sinh học', 130000, 2, 'Hóa học nền tảng, bài tập vừa sức.'),
        ('tutor25@gmail.com', 20, 'Vật lý', 'Khoa học', 'Vật lý - Hóa học - Sinh học', 320000, 10, 'Vật lý nâng cao và ôn thi.'),
        ('tutor25@gmail.com', 13, 'Toán học', 'Khoa học', 'Toán học', 300000, 10, 'Toán nâng cao cho học sinh mục tiêu cao.'),
        ('tutor26@gmail.com', 4, 'TOEIC', 'Ngoại ngữ', 'Tiếng Anh', 190000, 3, 'TOEIC theo lộ trình ngắn gọn.'),
        ('tutor26@gmail.com', 1, 'Tiếng Anh', 'Ngoại ngữ', 'Tiếng Anh', 180000, 3, 'Tiếng Anh giao tiếp và ngữ pháp.'),
        ('tutor27@gmail.com', 3, 'IELTS', 'Ngoại ngữ', 'Tiếng Anh', 280000, 5, 'IELTS mục tiêu 6.5+.'),
        ('tutor27@gmail.com', 4, 'TOEIC', 'Ngoại ngữ', 'Tiếng Anh', 260000, 5, 'TOEIC 650+ và 750+.'),
        ('tutor28@gmail.com', 45, 'Spring Boot', 'Công nghệ thông tin', 'Web Development', 300000, 6, 'Spring Boot API và project backend.'),
        ('tutor28@gmail.com', 55, 'SQL', 'Công nghệ thông tin', 'Cơ sở dữ liệu', 280000, 6, 'SQL cho ứng dụng Java backend.'),
        ('tutor29@gmail.com', 1, 'Tiếng Anh', 'Ngoại ngữ', 'Tiếng Anh', 120000, 2, 'Tiếng Anh nền tảng cho học sinh cần lấy lại gốc.'),
        ('tutor30@gmail.com', 38, 'Java', 'Công nghệ thông tin', 'Lập trình', 200000, 3, 'Java cơ bản và OOP.'),
        ('tutor30@gmail.com', 42, 'Python', 'Công nghệ thông tin', 'Lập trình', 210000, 3, 'Python cơ bản và bài tập thực hành.')
),
inserted_subjects AS (
    INSERT INTO tutor_application_subjects (
        tutor_application_id, subject_id, subject_name, subject_category_name, subject_group_name,
        one_to_one_hourly_rate, experience_years, description, created_at, updated_at
    )
    SELECT app.id, seed.legacy_subject_id, seed.subject_name, seed.category_name, seed.group_name,
           seed.rate, seed.experience_years, seed.description, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    FROM app_subject_seed seed
    JOIN users app_user ON LOWER(app_user.email) = seed.email
    JOIN tutor_applications app ON app.user_id = app_user.id
    ON CONFLICT (tutor_application_id, subject_id) DO UPDATE SET
        subject_name = EXCLUDED.subject_name,
        subject_category_name = EXCLUDED.subject_category_name,
        subject_group_name = EXCLUDED.subject_group_name,
        one_to_one_hourly_rate = EXCLUDED.one_to_one_hourly_rate,
        experience_years = EXCLUDED.experience_years,
        description = EXCLUDED.description,
        updated_at = CURRENT_TIMESTAMP
    RETURNING id, subject_id
)
INSERT INTO tutor_application_subject_levels (tutor_application_subject_id, level)
SELECT inserted_subjects.id,
       CASE
           WHEN inserted_subjects.subject_id IN (1, 13, 20, 21) THEN 'UPPER_SECONDARY'
           WHEN inserted_subjects.subject_id IN (3, 4) THEN 'EXAM_PREPARATION'
           ELSE 'UNIVERSITY'
       END
FROM inserted_subjects
ON CONFLICT (tutor_application_subject_id, level) DO NOTHING;

SELECT setval('users_id_seq', GREATEST((SELECT COALESCE(MAX(id), 1) FROM users), nextval('users_id_seq')), TRUE);
SELECT setval('students_id_seq', GREATEST((SELECT COALESCE(MAX(id), 1) FROM students), nextval('students_id_seq')), TRUE);
SELECT setval('tutors_id_seq', GREATEST((SELECT COALESCE(MAX(id), 1) FROM tutors), nextval('tutors_id_seq')), TRUE);
SELECT setval('tutor_profiles_id_seq', GREATEST((SELECT COALESCE(MAX(id), 1) FROM tutor_profiles), nextval('tutor_profiles_id_seq')), TRUE);
SELECT setval('tutor_applications_id_seq', GREATEST((SELECT COALESCE(MAX(id), 1) FROM tutor_applications), nextval('tutor_applications_id_seq')), TRUE);
SELECT setval('tutor_application_subjects_id_seq', GREATEST((SELECT COALESCE(MAX(id), 1) FROM tutor_application_subjects), nextval('tutor_application_subjects_id_seq')), TRUE);
