package iuh.fit.account_service.shared.enums;

public enum AuditAction {
    REGISTERED,
    EMAIL_VERIFIED,
    PASSWORD_CHANGED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    SESSION_CREATED,
    SESSION_REVOKED,
    REFRESH_ROTATED,
    REFRESH_REUSE_DETECTED,
    LOGOUT,
    LOGOUT_ALL,
    PROFILE_UPDATED,
    STATUS_CHANGED
}