package iuh.fit.contract_service.blockchain;

public enum EscrowEventType {
    AGREEMENT_REGISTERED,
    AGREEMENT_FUNDED,
    SESSION_SETTLEMENT_PROPOSED,
    TUTOR_FRAUD_DISPUTE_OPENED,
    SESSION_SETTLED,
    TUTOR_FRAUD_DISPUTE_RESOLVED,
    AGREEMENT_COMPLETED,
    AGREEMENT_EXPIRED,
    AGREEMENT_CANCELLED,
    UNUSED_AMOUNT_REFUNDED
}
