spring.application.name=api-gateway
debug=${SPRING_BOOT_DEBUG:false}
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties],optional:file:backend/.env[.properties]
server.port=8080

spring.cloud.gateway.httpclient.connect-timeout=${GATEWAY_CONNECT_TIMEOUT_MS:3000}


spring.cloud.gateway.routes[0].id=account-service
spring.cloud.gateway.routes[0].uri=${ACCOUNT_SERVICE_URL:http://127.0.0.1:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**,/me/**,/admin/**,/tutor-applications/**

spring.cloud.gateway.routes[1].id=learning-service
spring.cloud.gateway.routes[1].uri=${LEARNING_SERVICE_URL:http://127.0.0.1:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/tutors/**,/subjects/**,/learning-requests/**,/classrooms/**,/sessions/**,/assignments/**,/submissions/**,/reviews/**

spring.cloud.gateway.routes[2].id=notification-service
spring.cloud.gateway.routes[2].uri=${NOTIFICATION_SERVICE_URL:http://127.0.0.1:8084}
spring.cloud.gateway.routes[2].predicates[0]=Path=/notifications/**,/chat/**,/ws/**

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns=${GATEWAY_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.access=read-only
