spring.application.name=account-service

spring.datasource.url=jdbc:postgresql://localhost:5432/kltn_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:account-service.sql
spring.sql.init.continue-on-error=false

jwt.secret=your-super-secret-key-for-kltn-account-service-2026-very-long
jwt.expiration=86400000

app.frontend-url=http://localhost:5173

# SMTP config for real OTP email sending.
# Use a Gmail App Password here, not your normal Gmail password.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thinhxauzai24@gmail.com
spring.mail.password=xwbscvdpbvdejiya
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
